### ISSUE TITLE
Incorrect displaying code blocks

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#104]
**Описание бага**
Четкое описание неправильного поведения приложения.

Нет переносов в блоках кода

**Шаги для повторения бага**
1. https://habra.vercel.app/post/567646
2. https://habr.com/ru/post/567646/

**Ожидаемый результат**
Описание того, что должно было произойти.

Код не отображается одной строкой

**Скриншоты**
Прикрепите скриншоты бага, если таковое возможно.

Первое на habra, второе на хабре

![image](https://user-images.githubusercontent.com/43654815/126378365-0485873f-dc4c-4185-87bb-d8a5a6a16ca2.png)

![image](https://user-images.githubusercontent.com/43654815/126378264-dc9bef14-ba47-4ed3-9685-afe791d7963f.png)

**Информация об устройстве:**
 - OS: Linux, android
 - Браузер: Cromium-based, firefox
 - Версия браузера: [последняя]

**Комментарий**
Здесь можно написать что-нибудь дополнительно по проблеме.

**Comment by jarvis394** [comment]
Пофиксил в последнем коммите.
