### ISSUE TITLE
Обычная ссылка заменяются на ссылку ведующую на habra

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#106]
**Описание бага**

в коментарие на статью habra формирует относительную ссылку с таким путем `/post/470337/https://yandex.ru/championship/` в оригинальном коментарии была ссылка `https://yandex.ru/championship/`

**Шаги для повторения бага**
1. открыть статью https://habra.vercel.app/post/470337/comments
2. промотать до коментария 
![image](https://user-images.githubusercontent.com/26829359/127167802-f7871fc1-f25f-4105-99f9-add4a4a00aa0.png)

текст коментария для быстрого поиска: `… или поучаствовать в соревновании… чтобы устроиться к ним на работу)`

он рядом с концом первого треда

PS: судя по всему так заменяються все ссылки на внешние ресурсы

**Comment by centralhardware** [comment]
В последнем коментарии треда присутствует ссылка на habr.com которая не была заменена на habra.

![image](https://user-images.githubusercontent.com/26829359/127168754-70191027-1d9e-4c14-a953-00cb5ad19651.png)

**Comment by centralhardware** [comment]
В статьях так же заменяються
Например статья: https://habra.vercel.app/post/70330

![image](https://user-images.githubusercontent.com/26829359/127172332-4f91c61a-22ce-45d0-a890-4865bae930e4.png)

**Comment by jarvis394** [comment]
Функцию можно отключить в параметрах чтения.
