### ISSUE TITLE
Некоректное выделение ссылки в тексте статьи

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#109]
**Описание бага**

**Шаги для повторения бага**
1. открыть статью https://habra.vercel.app/company/gms/blog/518932
2. в последнем абзаце статьи будет ссылка 
![image](https://user-images.githubusercontent.com/26829359/127173869-fbe28e4b-7492-4404-828d-1490de077dd8.png)
в которой не выделилась `g_`

**Ожидаемый результат**

![image](https://user-images.githubusercontent.com/26829359/127173770-6f39cc1c-9809-435a-be67-945029941a7b.png)

скриншот с habr.com

**Comment by jarvis394** [comment]
<em> тэг просто выделяется цветом, `@g_` все равно кликабельна.
