### ISSUE TITLE
(было замечано) автоматическая замена habr.com -> habra.vercel.app, не учитвает наличие устаревшего домена habrahabr.ru

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#112]
Такая ссылка есть в https://habra.vercel.app/post/70330/comments

ссылка: habrahabr.ru/blogs/infosecurity/70330/#comment_2010652

**Comment by jarvis394** [comment]
Не будет фикситься, т.к. у старого хабра ссылки со старым форматом (`/blogs/infosecurity/70330` вместо `/post/70330`).

**Comment by jarvis394** [comment]
а в общем и целом мне просто лень
