### ISSUE TITLE
Сбрасывается фильтр лучшие за день

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#135]
**Шаги для повторения бага**
1. Открыть приложение убедившись что изначально на главной выбран фильтр лучшие за день
2. Перейти на вкладку новости
3. После перехода на главную вкладку будет выбран фильтр все подряд 

**Ожидаемый результат**
Фильтр не сбрасывается

**Комментарий**
Не критично, не мешает

**Comment by jarvis394** [comment]
После https://github.com/jarvis394/habra/commit/141277ec684e65aae43ce8bdfe46044f08746afa исправилось поведение? (надо нажать на кнопку "обновить приложение")

**Comment by centralhardware** [comment]
Да исправилось, воспроизвести не смог
