### ISSUE TITLE
Песочница 404 error

### ISSUE THREAD

**Issue by catterpiler74** [jarvis394/habra#139]
**Шаги для повторения бага**
1. Переходим хабы
2. Жмём песочница

**Ожидаемый результат**
Читать статьи из песочницы

**Скриншоты**
![Screenshot_20210912-153122](https://user-images.githubusercontent.com/1700920/132984256-1110d600-d178-40a1-99ea-875d7b9feff4.png)

**Информация об устройстве:**
 - OS: android 8.1
 - Браузер: chrome android
 - Версия браузера: [последняя]

**Комментарий**
Удобныц интерфейс просмотра хабры, спасибо!

**Comment by jarvis394** [comment]
Duplicate of #80
sandbox will be deployed in v3 probably :/
