### ISSUE TITLE
Move from Redux to MobX

### ISSUE THREAD

**Issue by jarvis394** [jarvis394/habra#15]
MobX is easier and more convenient to use than Redux, and it also doesn't require lot of boilerplate. Therefore, this should be in a roadmap

**Comment by jarvis394** [comment]
Migration process started

**Comment by angrypie** [comment]
Is it in progress?  Are you going to use mobx-react-lite or mobx-state-tree?

**Comment by Luchanso** [comment]
I think it's not necessary, try first use [@redux/tooklit](https://redux-toolkit.js.org/) maded from redux authors

**Comment by jarvis394** [comment]
> Is it in progress? Are you going to use mobx-react, mobx-react-lite (without classes) or mobx-state-tree?

Check `store/` in [mobx-iml branch](https://github.com/jarvis394/habra/tree/mobx-impl). Currently, I am using `mobx-react` library.

**Comment by jarvis394** [comment]
> I think it's not necessary, try first use [@redux/tooklit](https://redux-toolkit.js.org/) maded from redux authors

It probably is but with MobX you can easily create stores without lots of boilerplate. Also, it is easier to use in components, where you don't have to do dispatch - you only have to observe your variables.

For now, project is perfectly working on Redux, so this change anyway will be fulfilled in very distant future.

**Comment by jarvis394** [comment]
Might reopen later, don't know if I want to implement this.
