### ISSUE TITLE
Suggestions & improves

### ISSUE THREAD

**Issue by Luchanso** [jarvis394/habra#32]
Продублирую сюда:
> Если браузер устройства не поддерживает Service Worker, то эта страница всегда будет отображаться. Ну и при первом открытии пользователи всегда будут видеть 404 страницу.
> 
> Эта проблема (context root'а или pathname) исправляется простыми двумя скриптами в 404.html и index.html.
>
> Вообще это не единственная проблема с Service Worker, но у вас вроде отдельный домен, поэтому не должно больше вызывать сложностей.
1. Как это исправить [описано тут](https://github.com/rafgraph/spa-github-pages)
2. За место mobx можно сначала попробовать концепцию @redux/toolkit (но это всего лишь предложение, решать вам)
3. [Есть](https://github.com/jarvis394/habra/blob/master/src/components/blocks/NewsBlock.tsx) [жирные](https://github.com/jarvis394/habra/blob/master/src/components/blocks/PostItem.tsx) [компоненты](https://github.com/jarvis394/habra/blob/master/src/components/blocks/UserAvatar.tsx) без memo
4. В целом проект не плохо написан, вы молодец, продолжайте в том же духе!)

**Comment by Luchanso** [comment]
5. [В таких местах](https://github.com/jarvis394/habra/blob/master/src/store/actions/hubs.ts#L29) есть интересный кейс - что если запрос не успел завершиться, а пользователь делает действие которое вызывает повторно запрос? Интересен этот кейс ещё тем, что второй запрос может завершиться раньше первого

**Comment by Luchanso** [comment]
6. Старайтесь меньше пользоваться конструкциями `const initialState = {} as State`, лучше написать `const initialState:State= {}`, а уже в интерфейсе State сделать поля опциональными через знак вопроса: `State = { blabla?: number; }`

**Comment by Luchanso** [comment]
7. Команду lint нужно запускать не только на CI, но и на прекомит хуке, чтобы она отформатировала весь код. Для прекомит хуков можно использовать [Husky](https://typicode.github.io/husky/#/)

**Comment by jarvis394** [comment]
> 1. Как это исправить описано тут

Fixed in fd4da60
