### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by LencoDigitexer** [jarvis394/habra#35]
How to run script.

I download Node and install TypeScript.

Command:
```
D:\github.com\habra\src>tsc index.tsx 
```
is fail(((
Write is this and more
```
index.tsx:1:24 - error TS2307: Cannot find module 'react' or its corresponding type declarations.
```

I'm a complete noob in JavaScript

**Comment by jarvis394** [comment]
You have to run `npm run start:dev`.

For building a project you run `npm run build`.

For other scripts you can look up in package.json - you have to run them starting with `npm run`
