### ISSUE TITLE
"Open in habra."

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#37]
Extension for browser (work on habr.com) with ability open in habra.

**Comment by Levitanus** [comment]
Or, as an option — change links in the body of article.

**Comment by istudyatuni** [comment]
It's maybe bad, because "Тебе нужно зарегестрировать одну вещь - специального воркера ..."

**Comment by Levitanus** [comment]
> Тебе нужно зарегестрировать одну вещь - специального воркера ...

зачем? Я, правда, исходники не смотрел, но разве обязательно это делать уже на странице? Какой-то минимальный бэкенд же всё равно тут есть?

**Comment by istudyatuni** [comment]
Я тоже не смотрел ¯\_(ツ)_/¯

**Comment by jarvis394** [comment]
> Or, as an option — change links in the body of article.

Planned.

> зачем? Я, правда, исходники не смотрел, но разве обязательно это делать уже на странице? Какой-то минимальный бэкенд же всё равно тут есть?

Особенности Github Pages. Надо нормальный хостинг поднимать, либо решать иными путями.

**Comment by LencoDigitexer** [comment]
Т.е. если на странице будет ссылка, например, на https://habr.com/ru/post/527024/ то почему бы и не открывать хабру, а не хабр. ибо открывается хабр, хотя я не хочу покидать приложение habra. 
т.е. просто сделать перенаправление и заменить habr.com на регулярное habra.js.org в адресной строке.

```
let url = "https://habr.com/ru/post/527024/"

let re = /\habr.com\/ru/gi;
let result = url.replace(re, "habra.js.org");

console.log(result)
```

**Comment by istudyatuni** [comment]
> let re = /\habr.com\/ru/gi;
> let result = url.replace(re, "habra.js.org");

Иногда бывает что то типа habr.com/ru/company/blog/post/...

**Comment by jarvis394** [comment]
Merged to #49
