### ISSUE TITLE
Pictures are rendering in a wrong way

### ISSUE THREAD

**Issue by k2589** [jarvis394/habra#40]
Expected: to be rendered as on m. Habr.com (article: https://m.habr.com/ru/post/526946/)

![image](https://user-images.githubusercontent.com/6420066/98462436-8cd56000-21c5-11eb-809f-3555f5162c2a.png)

Current state:
![image](https://user-images.githubusercontent.com/6420066/98462437-94950480-21c5-11eb-89c3-64ff8facc286.png)

**Comment by jarvis394** [comment]
Cannot reproduce that in Chrome, can you share your device model and browser version?

![image](https://user-images.githubusercontent.com/37776763/98463296-44b93c00-21cb-11eb-854d-891d8f8c0771.png)

**Comment by k2589** [comment]
> @k2589
> 
> Cannot reproduce that in Chrome, can you share your device model and browser version?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37776763/98463296-44b93c00-21cb-11eb-854d-891d8f8c0771.png)
> 
> 
> 
> Edit: probably display: flex bug

iPhone 11, iOS 14.0, Safari

**Comment by jarvis394** [comment]
Did 9a7ce380a700db2b630d4c1fabf9d9d1481e39e5 fix the issue?

**Comment by k2589** [comment]
> Did [9a7ce38](https://github.com/jarvis394/habra/commit/9a7ce380a700db2b630d4c1fabf9d9d1481e39e5) fix the issue?

Nope:( Issue still exists 
![image](https://user-images.githubusercontent.com/6420066/98654168-064c8a00-234f-11eb-9632-e2ce5b45210d.png)

**Comment by jarvis394** [comment]
Have you updated the SW? Try clearing site's cache and data.

Needs more investigation. I don't have such device so I cannot really fix this issue. Might be solved somewhere in StackOverflow.

**Comment by jarvis394** [comment]
Check if 5e54b3359cbc8a33ad5ed0be1f2c66cbafc67b7c fixed the issue

**Comment by k2589** [comment]
> Check if 5e54b3359cbc8a33ad5ed0be1f2c66cbafc67b7c fixed the issue

Now everything works fine! Thank you!

**Comment by jarvis394** [comment]
Glad to see that!
