### ISSUE TITLE
 Dark text on dark background

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#41]
![Screenshot_20201111-091740613.jpg](https://user-images.githubusercontent.com/43654815/98775780-d78dec80-23fe-11eb-8c5c-fd8ec70ea274.jpg)![Screenshot_20201111-091750383.jpg](https://user-images.githubusercontent.com/43654815/98775789-dbba0a00-23fe-11eb-9880-2edac03a861a.jpg)
Может от статьи конечно зависит https://habra.js.org/post/527296. 
Когда включил светлую тему ![Screenshot_20201111-092154464.jpg](https://user-images.githubusercontent.com/43654815/98776075-5aaf4280-23ff-11eb-8d7f-34e08e4d94f2.jpg)

**Comment by istudyatuni** [comment]
Теперь везде не грузит :(

**Comment by jarvis394** [comment]
Это проблема с мегапостами; я на них не смотрел ещё.

**Comment by istudyatuni** [comment]
Уже норм) А так - оставался сплеш предзагрузки контента (не знаю, как это правильно называется)

**Comment by centralhardware** [comment]
Словил такое на этом https://habra.js.org/post/531370

**Comment by jarvis394** [comment]
Ещё раз:

> Это проблема с мегапостами; я на них не смотрел ещё.

В новом интерфейсе будет сделано.

![_hhmyfiufol2sukch2qejylegbq](https://user-images.githubusercontent.com/37776763/101393990-f639b300-38d8-11eb-8c58-9977625dfdeb.png)
