### ISSUE TITLE
Лучшие за год

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#44]
В мобильной версии почему то максимальный промежуток для лучших статей месяц, хотелось бы иметь лучшие за год и в мобильной версии

**Comment by jarvis394** [comment]
К сожалению, в мобильном API нет поддержки для лучших статей за год, а в десктопной версии идёт рендеринг на стороне сервера. Поэтому, пока что, такой фичи не будет.

**Comment by centralhardware** [comment]
closed by #56
