### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#45]

**Comment by jarvis394** [comment]
How is Docker good for a static website? Now, it is being hosted on GitHub Pages and autobuilds on a new commit. For Docker I would have to run a server, manage updates and CI and, most importantly, pay for something I can do for free. So I don't really see good things in deploying through Docker, maybe you can point on them?

**Comment by centralhardware** [comment]
you can use whatever is convenient for you, however, for everyone who wants to run your own version, docker will save a lot of time and nerves
