### ISSUE TITLE
Увеличение изображений по нажатию

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#48]
На смартфоне довольно трудно рассмотреть содержимое картинок без раскрытие на весь экран и увеличение

**Comment by jarvis394** [comment]
Было в прошлых версиях, сейчас надо дружить [react-lazy-load-image-component](https://www.npmjs.com/package/react-lazy-load-image-component) с [react-photoswipe](https://www.npmjs.com/package/react-photoswipe).

**Comment by jarvis394** [comment]
Готово в `redesign` ветке: можно посмотреть на сайте с бетой - https://habra.jarvis394.repl.co/
