### ISSUE TITLE
Не рендерится latex

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#51]
В математических статьях встречается latex как тут https://habra.js.org/post/528142 который на десктопе рендерится а на мобильной остаются в исходном виде 

$$display$$5=101_2=1*x^2+0*x^1+1*x^0=x^2+1$$display$$

**Comment by jarvis394** [comment]
У меня всё рендерится:

![IMG_20201116_100516](https://user-images.githubusercontent.com/37776763/99222271-439f9480-27f3-11eb-857d-b33af852d8b2.jpg)
