### ISSUE TITLE
Расшифровка рейтинга у статей и комментариев

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#53]
вертится на уме, то что официальная мобильная версия при нажатие на рейтинг показывает сколько было голосов за и против, сам пользовался пару раз для комментариев, может будет полезно, не знаю

![image](https://user-images.githubusercontent.com/26829359/99614151-8360b900-2a4b-11eb-8e5a-e5ba41f5de56.png)

так оно выглядит на оф версии

**Comment by jarvis394** [comment]
![image](https://user-images.githubusercontent.com/37776763/99685995-3523d800-2a94-11eb-9e35-a15aaccbdeee.png)

Разница между значениями - кол-во голосов против.
