### ISSUE TITLE
Назад по свайпу влево

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#54]
Удобно если нету возможности дотянуться одним пальцем до кнопки

**Comment by jarvis394** [comment]
Вроде, после 10 андроида можно включить управление жестами и там как раз есть свайп влево, который возвращает пользователя на предыдущую страницу в приложении. Если делать такое вручную, может быть проблема совместимости с нативным жестом "назад". 

Вполне можно сделать кнопку назад, но я не уверен, как влезет иконка в навбаре (хотел ещё сделать sidebar и к нему как раз нужна иконка)
