### ISSUE TITLE
I made a browser extension to redirecting from habr.com

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#55]
Как это занести в твой проект? Имею ввиду, создать папку какую-то с кодом, или как лучше сделать?

**Comment by centralhardware** [comment]
PR само собой, это если данный расширение вообще должен находится здечь, по идее лучше вынести в отдельный репозиторий, а все это в организации, ИМХО

**Comment by istudyatuni** [comment]
О, организация наверное идея получше)

**Comment by jarvis394** [comment]
Про организацию идея, кстати, хорошая. Тогда вопрос можно ли репозиторий из юзера в организацию перенести.

Пока можете оставить репозиторий у себя, сделайте PR на изменение readme и добавьте туда ссылку на свой репозиторий:

-----

## Extensions

Open on "habra.": [click]()

**Comment by centralhardware** [comment]
> Тогда вопрос можно ли репозиторий из юзера в организацию перенести

да

**Comment by istudyatuni** [comment]
[pull](https://github.com/jarvis394/habra/pull/57)

**Comment by jarvis394** [comment]
https://jarvis394.gitbook.io/habra/extensions
Добавил в доки.

**Comment by istudyatuni** [comment]
Там в доках не совсем корректно - я беру из url только номер поста
