### ISSUE TITLE
Выпадающее меню выбора лучших снизу

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#59]
В новом варианте не очень логично что вызывается по старой кнопке + неудобно что сначало надо нажимать сверху а потом снизу, может кнопку перенести вниз

**Comment by centralhardware** [comment]
PS без анимации смотрится довольно топорной, выбивает из общее картины

**Comment by jarvis394** [comment]
> PS без анимации смотрится довольно топорной

Должна быть анимация выезжания карточки. Если вы про кнопки, то это ещё не конечный вариант.

> может кнопку перенести вниз
Ещё подумаю, т.к. я планировал полный редизайн приложения.
