### ISSUE TITLE
Возможно баг

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#60]
![Screenshot_20201121_092755_com android chrome](https://user-images.githubusercontent.com/26829359/99865538-0cf3c080-2bdd-11eb-9da2-b175daa5a4dd.jpg)

Под статьей "как я нашел..."  синий прямоугольник

**Comment by jarvis394** [comment]
Fixed in 2fc1acbbe08c561cbb299384b41a0ca7217ddc6e
