### ISSUE TITLE
Toggle theme by time

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#62]
Например, после 6 утра - светлая, после 18 - темная. Время задать в настройках

**Comment by centralhardware** [comment]
не знаю можно ли такое сделать, но ведь можно выбирать тему в зависимости от того какая системная

**Comment by jarvis394** [comment]
> не знаю можно ли такое сделать, но ведь можно выбирать тему в зависимости от того какая системная

Можно: https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript

**Comment by istudyatuni** [comment]
Тема которая следует за системной это круто, но это скорее всего не будет работать на линуксе. Да и насчет андроида не очень уверен

**Comment by istudyatuni** [comment]
А по времени примерно так: если больше 6 и меньше 18 - светлая, если 18-24(0) или 0-6, то темная. Правда надо будет учесть, если кто-нибудь поставит наоборот, например, светлая  после 18

**Comment by jarvis394** [comment]
Сейчас времени нет

**Comment by jarvis394** [comment]
Сейчас нет времени делать фичи, на данный момент сфокусирован на производительности и авторизации.

В доках можете найти инструкцию, как контрибутить в проект - флаг в руки!

**Comment by centralhardware** [comment]
@istudyatuni  

> но это скорее всего не будет работать на линуксе

а причем тут вообще линукс

**Comment by istudyatuni** [comment]
> а причем тут вообще линукс

Кроссплатформа как никак)
А так - я например на линуксе, мне удобней будет просто задать временные промежутки

**Comment by centralhardware** [comment]
У вас на телефоне Линукс?

**Comment by centralhardware** [comment]
Использовать habra можно и на десктопе, но зачем, верстка заточена только для смартфонов

**Comment by jarvis394** [comment]
> Использовать habra можно и на десктопе, но зачем, верстка заточена только для смартфонов

В будущем будет (надеюсь) оптимизировано для md-lg экранов (планшеты).

**Comment by istudyatuni** [comment]
> У вас на телефоне Линукс?

Ну чисто формально да) Линукс у меня на компе
А насчет того, что верстка заточена **только** под телефоны, не знал

**Comment by centralhardware** [comment]
![image](https://user-images.githubusercontent.com/26829359/100207611-5e33e500-2f3a-11eb-803e-f135b8cad7d5.png)
мы либо вернулись в 2010 десятый, либо это мобильная верстка

**Comment by istudyatuni** [comment]
Я бы поспорил, смысл делать контент посередине страницы для того, чтобы было легче читать. Для сравнения - попробуйте почитать информацию на каком-нибудь сайте, где не используются кастомные css стили, и текст располагается на всю ширину страницы. Это довольно тяжело, как по мне

**Comment by centralhardware** [comment]
посмотрите на оригинальный десктоп хабр, там то же контент по середине не на всю ширину, но там верстка это не растянутые на fulhd элементы, которые явно не были на это расчитаны

**Comment by istudyatuni** [comment]
> растянутые на fulhd элементы
Такие моменты даже не замечаю) но это наверное из-за Mui

**Comment by jarvis394** [comment]
> Тема которая следует за системной это круто, но это скорее всего не будет работать на линуксе. Да и насчет андроида не очень уверен

@istudyatuni , делаю в v2
