### ISSUE TITLE
Incorrect image size when image is small

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#70]
https://habra.js.org/post/531404

В конце статьи, где рассматриваются плюсы и минусы, эти картинки гигантские, а на хабре маленкие

**Comment by jarvis394** [comment]
Нужно хандлить свойства `width` и `height` у <img /> при парсинге текста статьи.

**Comment by istudyatuni** [comment]
https://habra.js.org/post/537610/comments
Во, здесь похожая штука в комментах

**Comment by jarvis394** [comment]
Пофиксил в v2 (redesign ветка)

**Comment by istudyatuni** [comment]
Выглядит суперски)
