### ISSUE TITLE
Incorrect opening habr links

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#71]
![image](https://user-images.githubusercontent.com/43654815/101878133-21a1f380-3ba0-11eb-8d59-98a7d0fedd2c.png)
Курсор не попал на скриншот
![image](https://user-images.githubusercontent.com/43654815/101878241-4ac28400-3ba0-11eb-9a7f-18231ee5e953.png)
Не уверен, это замена, или изначально была такая ссылка
https://habra.js.org/post/527218

**Comment by jarvis394** [comment]
Вопрос сюда: https://github.com/istudyatuni/habra-redirect

**Comment by istudyatuni** [comment]
В том то и дело, что это при выключенном расширении сохраняется. Расширение то меняет адрес только при запросе, а само тело страницы не трогает. А такая ссылка даже в оригинальной статье на хабре. Вот например, как выглядят другие ссылки 
![image](https://user-images.githubusercontent.com/43654815/101899474-efec5500-3bbe-11eb-9421-fe0dab86df19.png)
Наверное проблема в том, что когда явно не указан хост, открывается на том же, на котором происходит клик по ссылке (в данном случае, на habra.js.org)
Для проверки, можете попробовать перейти по той ссылке с телефона, где расширения в браузерах точно не поддерживаются

**Comment by istudyatuni** [comment]
@jarvis394 может переоткрыть issue?

**Comment by jarvis394** [comment]
Нужно парсить ссылки, которые ссылаются на `habr.com` или на корень сайта, и подменять их на корень сайта (`habra.js.org`). К тому же, нужно убирать всё лишнее в ссылках (`ru` в `habr.com/ru/post/...`)

**Comment by istudyatuni** [comment]
https://regex101.com/r/JZ46fx/3
вот regex который я использую в habra-redirect. но тут правда я не уверен что отслеживаются все случаи, потому что могут быть какие нибудь еще виды ссылок. да и тот же sandbox пока что непонятно как обрабатывать

**Comment by istudyatuni** [comment]
Возможно стоит сделать как то так:

```js
let links = document.querySelectorAll('a')
links.forEach((e) => {
    e.onclick = () => {
        // do redirect, if link points to habr.com
    }
})
```
