### ISSUE TITLE
ошибка авторизации на андройд

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#73]
проблема проявляется на:

![image](https://user-images.githubusercontent.com/26829359/102684081-26058680-4208-11eb-915d-df4d66770538.png)

```
3664-4167/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Access to fetch at 'https://habr.com/auth/o/access-token' from origin 'https://habra.js.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.", source:  (0)
3664-4167/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "The FetchEvent for "https://habr.com/auth/o/access-token" resulted in a network error response: the promise was rejected.", source:  (0)
```
логи получены с:

![image](https://user-images.githubusercontent.com/26829359/102684129-885e8700-4208-11eb-9b7f-ed168b5846cc.png)

PS: на ipad с версией ios 14,2, вход работает 😊

**Comment by jarvis394** [comment]
https://github.com/jarvis394/habra/discussions/69 - там написано про мобильные девайсы. Хотя у меня получение токена работало с телефона, странно. Если придётся через прокси делать авторизацию, это провал.

**Comment by centralhardware** [comment]
А какой у вас телефон, прогнал на эмуляторах 7-11 версии андройда и везде не работает

**Comment by jarvis394** [comment]
![IMG_20201223_144635](https://user-images.githubusercontent.com/37776763/102993156-b6580a00-452d-11eb-8e6b-caa3d88762ab.jpg)
Последний Chrome, 10 андроид (MIUI 11.2)

Эмуляторы могут дополнительные заголовки отправлять и поэтому может не проходить запрос.

**Comment by centralhardware** [comment]
подрубил удаленный дебагер хрома и токен получается успешно, однако в логе

![Screenshot_20201223_195832](https://user-images.githubusercontent.com/26829359/102998374-a22a0200-4559-11eb-89c3-039a43b792eb.jpg)

**Comment by jarvis394** [comment]
Без прокси не грузится основное API (в данном случае `users/me`)

**Comment by centralhardware** [comment]
Теперь пишет что неверный логин или пароль хотя они верный (менеджер паролей)

**Comment by sprainbrains** [comment]
> Теперь пишет что неверный логин или пароль хотя они верный (менеджер паролей)

Такая же проблема, но уже на дектопе на Маке

**Comment by centralhardware** [comment]
Попробуйте кеш сбросить, у меня проблема прошла

**Comment by jarvis394** [comment]
> Без прокси не грузится основное API (в данном случае users/me)
Сейчас не работает даже авторизация, поэтому будет всегда говорить "Неправильный пароль", т.к. сам запрос не проходит.

**Comment by sprainbrains** [comment]
> > Без прокси не грузится основное API (в данном случае users/me)
> 
> Сейчас не работает даже авторизация, поэтому будет всегда говорить "Неправильный пароль", т.к. сам запрос не проходит.

хабр апи поменял ?

**Comment by jarvis394** [comment]
Не знаю, но они могут вообще это апи закрыть.
Поэтому я сейчас редизайном занимаюсь, а не api. Сейчас новую версию сайта можно посмотреть [тут](https://habra.jarvis394.repl.co/)

**Comment by jarvis394** [comment]
Closed due to inactivity.
