### ISSUE TITLE
статься без заголовка

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#74]
https://habra.js.org/search/p/1?q=%D1%85%D0%B0%D0%B1%D1%80%D0%B0%D1%87%D0%B0%D1%82
при следующем поиске появляется статься без заголовка:

![image](https://user-images.githubusercontent.com/26829359/102982845-c972d600-453d-11eb-8e01-9d5e2a448628.png)

при попытке открыть коментарии

![image](https://user-images.githubusercontent.com/26829359/102982906-db547900-453d-11eb-954c-2e9feaf0fbf1.png)

![image](https://user-images.githubusercontent.com/26829359/102983070-1b1b6080-453e-11eb-877f-7da179cec065.png)

`https://m.habr.com/kek/v2/articles/482600/comments?fl=ru&hl=ru`

в профиле у этого пользователя показывает что публикаций у него не было

**Comment by jarvis394** [comment]
Скорее всего баг Хабра, у них были проблемы со статьями в старом формате.

**Comment by centralhardware** [comment]
да действительно проблема хабра
