### ISSUE TITLE
Нельзя выделить кликабельный текст

### ISSUE THREAD

**Issue by Rult** [jarvis394/habra#75]
Текст, в котором есть ссылка, нельзя выделить.

**Comment by jarvis394** [comment]
Какой девайс вы используете?
На телефоне, при долгом нажатии на ссылку, можно скопировать её текст.

**Comment by Rult** [comment]
Вы не так поняли, смотрите

![image](https://user-images.githubusercontent.com/20477460/103419188-dc168c00-4b89-11eb-9c07-ec173dc1dbdd.png)

Из этого сохраняется в буфер вот это

`SSH чат: хост: , порт 22. Для подключения к SSH-чату можно использовать любой SSH-клиент. Например, .`

**Comment by Rult** [comment]
> Какой девайс вы используете?
> На телефоне, при долгом нажатии на ссылку, можно скопировать её текст.

Кстати, при долгом нажатии на любом устройстве из `habr2021.podivilov.ru` копируется `https://habra.js.org/post/habr2021.podivilov.ru`
