### ISSUE TITLE
Direct link to comment?

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#79]
Есть ли сейчас возможность скопировать ссылку на определенный комментарий, а не просто ./comments ?
https://habr.com/ru/post/535936/#comment_22501886
Например, что то типа этого

**Comment by istudyatuni** [comment]
@jarvis394, крутяк! А возможно сделать, чтобы комментарий как то выделялся (например, вроде обводки что-нибудь), просто если например комментарий находится ниже, то прокрутка идет не строго до него, и не понятно, на какой комментарий ссылка

**Comment by jarvis394** [comment]
да, знаю про это. С выделением комментариев проблема, т.к. мне (насколько я помню) не получилось в useEffect получать актуальный референс на dom объект комментария. У меня комментарии сначала скрыты плейсхолдером, а при прокрутке рендерятся уже сами комментарии. И useEffect поначалу получает именно плейсхолдер и пытается применить анимацию выделения ему, а не настоящему комментарию. Пока не знаю, что можно с этим сделать.

**Comment by jarvis394** [comment]
+ у комментариев будет по нажатию на три точки открываться меню, где можно скопировать url и перейти в профиль автора
