### ISSUE TITLE
Post absolutely not displayed 

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#87]
**Описание бага**
Четкое описание неправильного поведения приложения.

Этот пост https://habra.js.org/post/544864 не отображается (совсем, белая страница)

**Шаги для повторения бага**
1. Зайти по ссылке

**Ожидаемый результат**
Описание того, что должно было произойти.

Статью видно

**Скриншоты**
Прикрепите скриншоты бага, если таковое возможно.

Ничего не видно :)

**Информация об устройстве:**
 - OS: Linux Manjaro
 - Браузер: Vivaldi stable
 - Версия браузера: [последняя]

**Комментарий**
Здесь можно написать что-нибудь дополнительно по проблеме.

Тоже самое и на телефоне. В chromium на пк тоже

**Comment by centralhardware** [comment]
аналогично

**Comment by jarvis394** [comment]
Странно, приложение падает здесь:
https://github.com/jarvis394/habra/blob/2fc8e2787e717a581be30a4e927a973ed53141e4/src/pages/Post/index.tsx#L241

На других корпоративных статьях всё нормально: [вот например](https://habra.vercel.app/company/flant/blog/545640).

Возможно, проблема на стороне Хабра. На самом сайте они почему то не получают данные компании, но эти данные откуда-то появляются.

**Comment by istudyatuni** [comment]
https://habra.js.org/post/546192
Ещё нашёл
