### ISSUE TITLE
Выпуск на смартфоны.

### ISSUE THREAD

**Issue by KR1470R** [jarvis394/habra#89]
Здраствуйте, очень понравился ваш ребилд Хабра. 
Было бы очень здорово выпустить его на Play Market и App Store.

**Comment by centralhardware** [comment]
Можно сделать, однако ничего не поменяется кроме способа установки

**Comment by KR1470R** [comment]
Согласен, но кто-то уже должен сделать НОРМАЛЬНЫЙ мобильный клиент для Хабра)

**Comment by jarvis394** [comment]
![IMG_20210306_192252](https://user-images.githubusercontent.com/37776763/110213540-95a71b80-7eb1-11eb-9b26-c29686b42d95.jpg)
![IMG_20210306_192347](https://user-images.githubusercontent.com/37776763/110213543-96d84880-7eb1-11eb-8f1b-98ac8e69072b.jpg)

 Профит.

______

Если делать приложение на дроид/айось, то на чём писать? React Native? Изучать Kotlin? Что мне, как разработчику, даст переход в натив (кроме скорости)?

Я веб разработчик, работа с нативными приложениями мне незнакома. Это не значит, что я боюсь изучать новое, просто, серьезно, какое различе будет между тем, что ты добавил сайт как приложение или скачал тот же сайт, но в виде нативного приложения? Я не вижу смысла переписывать проект в натив.

**Comment by centralhardware** [comment]
ИМХО, если уж переписывать на флатер там можно сразу и ios и android и web сразу, а по поводу установки PWA через google play, то там насколько я знаю ничего переписывать не надо, просто на github есть проект, который позволяет запаковать PWA в приложение приодное для публикации

**Comment by jarvis394** [comment]
@centralhardware, ещё раз, главный вопрос - **зачем?** Зачем переписывать, выкладывать куда-то (в GP, кстати, платить надо), если можно и так сайт установить как приложение. Красота PWA именно в этом - один клик и готово.

**Comment by centralhardware** [comment]
Ну так я пишу что ничего не поменяется

**Comment by centralhardware** [comment]
Ну допуская то что кто то не знает про PWA сделать плашку с объяснением при первом запуске и все

**Comment by jarvis394** [comment]
> Ну допуская то что кто то не знает про PWA сделать плашку с объяснением при первом запуске и все

Это я и намеревался сделать :) Можно программно по нажатию кнопки запускать окошко добавления PWA.
