### ISSUE TITLE
обрезается фото (в новой версии)

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/habra#93]
**Описание бага**

ферх фото превью обрезается, на экране типа ipad и больше

**Скриншоты**

![image](https://user-images.githubusercontent.com/26829359/111499255-5318f500-8775-11eb-9446-ebfe07174a22.png)

**Comment by jarvis394** [comment]
Так и задумано:

https://github.com/jarvis394/habra/blob/14dec9f8097f9e6ef22cf447c0f3a817f1791b14/src/config/constants.ts#L20

Опять же, я пока не оптимизировал сайт для остальных устройств, кроме смартфона, поэтому на компьютере выглядит не очень.

Меня больше волнует то, что у вас не прогружены шрифты. Должно выглядеть так:

![image](https://user-images.githubusercontent.com/37776763/111505338-949ba700-8759-11eb-83ee-e73a9cc7846b.png)
