### ISSUE TITLE
Absolutely not work

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#94]
**Описание бага**
Совсем не открывается, сначала висит плашка загрузки, потом белый экран

**Информация об устройстве:**
Linux, android, во всех установленных браузерах (чистый хром, firefox, и не только)

**Дополнительно**
![image](https://user-images.githubusercontent.com/43654815/113294149-4fea4100-92ff-11eb-88ad-a4b02452b420.png)
`Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.`

Это не единственная ошибка, там еще несколько появляется, но они могут не иметь отношения к этому

**Comment by jarvis394** [comment]
Уточню, это к какой версии приложения относится? Сейчас есть приложение на ветке **redesign** (habra.vercel.app), и на ветке **master** (habra.js.org).

> Это не единственная ошибка

 было бы неплохо увидеть все логи!

**Comment by istudyatuni** [comment]
К версии js.org
Логи:
![image](https://user-images.githubusercontent.com/43654815/113295817-58437b80-9301-11eb-9415-7f6a9105a0e2.png)
Файл: [habra.js.org-1617281165097.log](https://github.com/jarvis394/habra/files/6243554/habra.js.org-1617281165097.log)
*Google analitics блокируется адблоком, но если выключить блокировку, все равно не работает*

**Comment by jarvis394** [comment]
```
Unexpected token '!'
```

Нужно будет ещё перенести с новой ветки файл serviceWorker, а то он и тут свалился. Почему-то библиотека не парсит мои файлы и тупо выдаёт `undefined` в начале:

https://github.com/jarvis394/habra/blob/1ac61e61fa2bf5ed479bef19c6d61c56c695b7cc/service-worker.js#L1

**Comment by jarvis394** [comment]
Так или иначе, на хабре поменяли API у статей, а именно убрали тэги из объекта. Поэтому на начальном экране всё падало, т.к. приложение шло по несуществующему пути в объекте.

**Comment by istudyatuni** [comment]
@jarvis394 опять :(
![image](https://user-images.githubusercontent.com/43654815/113300200-5c25cc80-9306-11eb-826b-db5f494ac3af.png)
https://habra.js.org/post/550072
Причем другие посты открываются

**Comment by jarvis394** [comment]
Попробуйте очистить куки и кэш страницы. service-worker подгружает старое приложение без фикса.

**Comment by istudyatuni** [comment]
Не помогает. Даже в приватном режиме остается. Но вообще тут видимо дело в том, что ошибка та же, но файл уже другой - index.tsx
![image](https://user-images.githubusercontent.com/43654815/113303260-92188000-9309-11eb-95ac-43f9c91c796c.png)

**Comment by jarvis394** [comment]
Пофиксил.

**Comment by istudyatuni** [comment]
@jarvis394, привет! Опять похожая штука. Решил не создавать новый issue
![image](https://user-images.githubusercontent.com/43654815/114735710-1f1df900-9d4e-11eb-8ce5-19c2ab6c3fbc.png)
Не работает на главной, https://habra.js.org/post/551576 , https://habra.js.org/post/552308 , причем работает вот здесь https://habra.js.org/post/552206 . Еще встречается ошибка 
![image](https://user-images.githubusercontent.com/43654815/114736134-820f9000-9d4e-11eb-8233-6f237cbae20b.png)
но например в посте по самой последней ссылке она тоже есть, и ничего

**Comment by jarvis394** [comment]
Пофиксил в https://github.com/jarvis394/habra/commit/34de313d12b1464a0d9e5fe004965408f4778a28 на ветке `master` и https://github.com/jarvis394/habra/commit/822736c4c9427baf0b0cd87f18a5109361011750 на ветке `redesign`

**Comment by istudyatuni** [comment]
Ого, круто!
