### ISSUE TITLE
Перезагрузка страницы при открытии картинки

### ISSUE THREAD

**Issue by LencoDigitexer** [jarvis394/habra#95]
**Описание бага**
Обнаружил на этой странице - https://habra.js.org/post/552384/
При нажатии на первой картинке пытается открыться картинка в увеличенном размере, но страница перезагружается.
К примеру, на этой странице https://habra.js.org/post/553478 картинка тоже не открывается, но страница становится белой. А после её перезагрузки картинка нормально отображается без перезагрузки.

**Информация об устройстве:**
 - OS: windows 10
 - Браузер: chrome, edge
 - Версия браузера: [последняя]

**Комментарий**
Скорее всего, картинка имеет ссылку, т.е. она кликабельна на оригинальном хабре и перенаправляет на эту же страницу в посте.

**Comment by jarvis394** [comment]
> Скорее всего, картинка имеет ссылку, т.е. она кликабельна на оригинальном хабре и перенаправляет на эту же страницу в посте.

Именно это и является проблемой. Уже есть #71 про замену ссылок с habr на habra.

Думаю, нужно пофиксить поведение картинки с ссылкой, т.е. не открывать предпросмотр если есть тэг `<a href="">` на картинке.
