### ISSUE TITLE
Error after scrolling in full-screen image preview

### ISSUE THREAD

**Issue by istudyatuni** [jarvis394/habra#97]
**Описание бага**

Открываю изображение в полный экран, и скроллю - полностью белый экран

**Шаги для повторения бага**
1. Открыть изображение кликом по нему
2. Сдвинуть колесико мыши (как я понял, это для смахивания когда открываешь на телефоне)

**Ожидаемый результат**

Хотя бы не пропадет весь контент

**Скриншоты**

Там просто белый экран) Но есть логи 
![image](https://user-images.githubusercontent.com/43654815/116083736-a865f180-a6a5-11eb-93bc-c97cd88fbb04.png)

**Информация об устройстве:**
 - OS: Linux Manjaro
 - Браузер: Vivaldi (chromium-based), firefox
 - Версия браузера: [последняя]

**Комментарий**

*Без комментариев*

**Comment by jarvis394** [comment]
Для какой версии приложения относится баг? Есть версия v1 (ветка master, habra.js.org) и v2 (ветка redesign, habra.vercel.app). Я увидел баг только на habra.js.org

**Comment by istudyatuni** [comment]
Всегда забываю про это сказать) версия на habra.js.org

**Comment by jarvis394** [comment]
Нет идей по поводу фикса? Можете посмотреть [здесь](https://github.com/jarvis394/habra/blob/06d1d72e05c4bafe71aed2e5f067f3241d3a361b/src/components/blocks/LazyLoadImage.tsx) и сравнить с [этим](https://github.com/jarvis394/habra/blob/78a8adc0a4642c9962e89f5a3835f683b5992aeb/src/components/blocks/LazyLoadImage.tsx) файлом, т.к. на v2 всё работает.

**Comment by istudyatuni** [comment]
Пока что достал только это) 
![image](https://user-images.githubusercontent.com/43654815/116136992-b46ca600-a6db-11eb-9efd-2192ecf3b658.png)
Но это в самой библиотеке

**Comment by jarvis394** [comment]
Можно ещё ссылку на страницу с багом? На смартфоне, кстати, всё отлично работает. Возможно, нужно добавить `closeOnScroll: false` в `pswpOptions`:
https://github.com/jarvis394/habra/blob/06d1d72e05c4bafe71aed2e5f067f3241d3a361b/src/components/blocks/LazyLoadImage.tsx#L87

**Comment by istudyatuni** [comment]
Это как я понимаю происходит на любой странице, где можно открыть изображение. На телефоне да. Насчёт опции - на v2 же работает, чтобы закрывался без скролла

**Comment by istudyatuni** [comment]
Вау, а что вы изменили? Или как?
